/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kochkurve;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Frank
 */
public class Kurve1 {
  private int maxLevel = 4;
  private int gesamtLänge = 800;
  private String initiator = "F";
  private String generator = "FlFrrFlF";
  /**
   * Creates new form Kurve1
   */
  public Kurve1() {
    initComponents();
  }
  public Kurve1(int AnzahlLevel) {
    initComponents();
    maxLevel = AnzahlLevel;
  }
  public String KochkurveAlsText(int level) {
    return KochkurveAlsText(level, initiator);
  }
  public String KochkurveAlsText(int level, String kurve) {
    if (level >= maxLevel) {
      return kurve;
    } else {
      // ersetze alle initiatoren durch die Generatoren
      String neueGeneration = kurve.replaceAll(initiator, generator);
      return KochkurveAlsText(level+1,neueGeneration);
    }
  }
 /*  @Override public void paintComponent(Graphics g) {
    Graphics2D g2d = (Graphics2D) g;
    g2d.setColor(Color.blue);
    super.paintComponent(g2d);
    String k = KochkurveAlsText(maxLevel);
    double länge = gesamtLänge/Math.pow(3, maxLevel);
    double x = 100, y = 100, x1 = 0, y1 = 0, winkel = 0;
    for (char c: k.toCharArray()) {
      switch (c) {
        case 'F': 
          x1 = x + länge * Math.cos(winkel);
          y1 = x + länge * Math.sin(winkel);
          g2d.drawLine((int)x, (int)y, (int)x1, (int)y1);
          x = x1;
          y = y1;
          break;
        case 'l': 
          winkel += Math.PI/3;
          break;
        case 'r':
          winkel -= Math.PI/3;
          break;
      }
    }
  }
 */
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setPreferredSize(new java.awt.Dimension(800, 624));
    setRequestFocusEnabled(false);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 312, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
